### PR TITLE
BUG: Empty staff list shows student's empty state #232

### PR DESCRIPTION
**Pull request by hieungo89**
Referencing issue #232. I adjusted the specification of the empty state so Staff page shouldn't be affected by Student's list empty state anymore.

**Before:**
Screenshot 2023-11-03 at 10 11 17 AM

**After**:
Screenshot 2023-11-03 at 10 09 31 AM

### CODE REVIEW

**Review by codetheweb — APPROVED** [review]
should we edit the copy for the empty staff state instead?

**Comment by hieungo89** [comment]
> should we edit the copy for the empty staff state instead?

Niko confirmed that there won't be an empty staff state since the staff page will always have at least the current signed-in staff and never be empty.

**Review by tessathornberry — APPROVED** [review]
Looks great, Hieu! Nice work! Maybe we can make a separate issue to add the user to the staff list, too! What do you think?

**Comment by hieungo89** [comment]
> Looks great, Hieu! Nice work! Maybe we can make a separate issue to add the user to the staff list, too! What do you think?

I'm planning to work on that next. When staff sign in for the first time, their name is automatically added to the staff list so the list won't be empty.

**Pull request merged**
