### PR TITLE
added frequency to database schema 

### PR DESCRIPTION
**Pull request by j-h-li**
added frequency to database schema and changed subgoal functions to reflect updated data table

### CODE REVIEW

**Review by nickvisut — APPROVED** [review]
lgtm

**Comment by KCCPMG** [comment]
I updated this branch including refactoring the create benchmark page to re-work the checks and add some TextField validation. The page no longer throws an alert if the button is clicked before checks are passed, rather the buttons are disabled until every required field has valid input. @nickvisut and @BrettEastman , I would appreciate your eyes on it if you can since this is reworking some of what you both did in creating the create-benchmark page, hopefully everything makes sense.

**Review by BrettEastman — APPROVED** [review]
Hey, everything looks great and works properly! After resetting my database (tried migrating first but that didn't work), I was able to successfully input a new goal with new benchmarks without a problem on this branch. As you intended, the buttons are now disabled until all fields are filled-in. Great work, thanks for fully implementing the frequency field, @KCCPMG !

**Comment by KCCPMG** [comment]
> Hey, everything looks great and works properly! After resetting my database (tried migrating first but that didn't work), I was able to successfully input a new goal with new benchmarks without a problem on this branch. As you intended, the buttons are now disabled until all fields are filled-in. Great work, thanks for fully implementing the frequency field, @KCCPMG !

Thanks, Brett!

**Comment by katconnors** [comment]
Also looks good to me!

**Review by katconnors — APPROVED** [review]

**Pull request merged**
