### PR TITLE
364 ticket, changed subgoal to benchmark

### PR DESCRIPTION
**Pull request by j-h-li**
changed subgoal to benchmark

### CODE REVIEW

**Review by BeeSeeWhy — DISMISSED** [review]
The changes look good, but it looks like there are some conflicts that need to be resolved before we can merge. Also, I don't see components/benchmark folder added along the files, but I see components/subgoal files deleted. Should this all be deleted? 
Screenshot 2024-08-22 at 5 33 49 PM

**Comment by thomhickey** [comment]
> The changes look good, but it looks like there are some conflicts that need to be resolved before we can merge. Also, I don't see components/benchmark folder added along the files, but I see components/subgoal files deleted. Should this all be deleted? Screenshot 2024-08-22 at 5 33 49 PM

Yes @BeeSeeWhy, those files need to be replaced or references to them need to be removed, but the missing files are causing problems as there are still imports pointing to them.

**Comment by KCCPMG** [comment]
> The changes look good, but it looks like there are some conflicts that need to be resolved before we can merge. Also, I don't see components/benchmark folder added along the files, but I see components/subgoal files deleted. Should this all be deleted? Screenshot 2024-08-22 at 5 33 49 PM

I believe this is good to go. There is src/components/benchmarks, let me know if there's anything else that you notice as being out of place or missing.

**Comment by KCCPMG** [comment]
This should hopefully now be up to date and working in light off the most recent updates on main. @canjalal and @thomhickey, you may want to check specifically to make sure that the latest addSubgoal/addBenchmark tests haven't gotten mangled by the change in terms.

**Review by katconnors — COMMENTED** [review]
Comparing main vs this branch's behavior, there's something to note: 
when loading student pages that don't have benchmarks, there are 500 errors in the terminal, and the page is slow to load.

That being said, the code looked good prior to the behavior check, so I'm not sure what is causing this.

**Comment by KCCPMG** [comment]
> Comparing main vs this branch's behavior, there's something to note: when loading student pages that don't have benchmarks, there are 500 errors in the terminal, and the page is slow to load.
> 
> That being said, the code looked good prior to the behavior check, so I'm not sure what is causing this.

Thanks for the feedback, I'll take a look! I'm assuming this was after resetting the database? Were there any issues when doing so?

**Comment by KCCPMG** [comment]
> Updating to approve- no 500 errors after db reset.

Awesome, thank you, Katrina!

**Pull request merged**
